### ISSUE TITLE
<Calculator> vmcheker

### ISSUE THREAD

**Issue by Bassem-bk-1220** [UPB-FILS/alf#19]
I have problem that when i put the homework in the vmchecker  they give me some operations is not working but in the node js is working. If there is any solutions?

**Comment by RaduNicolaeEduard** [comment]
## Uniq
Your uniq works but it is printed as an array
## Subtract
subtract is not printing the correct answer, I think that you are subtracting from 0, and that's why your subtract isn't working
## Help / No commands
check if your program prints the exact thing as [this](https://github.com/UPB-FILS/alf/blob/master/Devoir/calculator/verify/calculator/1_folder.a_author.out), where it says alf there should be your name

## Tip
If you scroll down the vmcheker results you can see what are the expected results, they should be on the left and your results on the right

**Comment by Bassem-bk-1220** [comment]
![20200308_200100](https://user-images.githubusercontent.com/61603951/76168420-6a8fcc00-6178-11ea-9134-0781b6cb9f3c.jpg)
![20200308_200112](https://user-images.githubusercontent.com/61603951/76168430-767b8e00-6178-11ea-9030-152fc220ac53.jpg)
![20200308_200429](https://user-images.githubusercontent.com/61603951/76168435-7ed3c900-6178-11ea-98f8-ce59f808bb78.jpg)
I use the same exemple in the checker and in the nodejs is working and on the checker is not working ?any solution

**Comment by RaduNicolaeEduard** [comment]
It fails the check because you have a new line for each element, they should be with a space between
