### ISSUE TITLE
[calculator] Bonus

### ISSUE THREAD

**Issue by xproxidizzy** [UPB-FILS/alf#8]
Why does the tester check if there can be added more than 2 complex numbers if the sentence tells us to do with 2 complex numbers? There is also a check if you can add a real number to 2 complex numbers. In the sentence those are not mentioned.
The input format is clear:
"node main.js addition a1 b1 a2 b2 complex"
"node main.js subtraction  a1 b1 a2 b2 complex"
"node main.js multiply a1 b1 a2 b2 complex"

**Comment by JStudent97** [comment]
"Why does the tester check if there can be added more than 2 complex numbers if the sentence tells us to do with 2 complex numbers?"

https://imgur.com/dc9IWig

As seen in the photo above,  in the enunciation text it's not specified the number of complex numbers for which your functions should work :) it says : "implement the calculator to work for complex numbers for addition, subtraction and multiply" . 

Only the example it's given with 2 numbers in order to clarify how you should call the "complex" functions.

"There is also a check if you can add a real number to 2 complex numbers. In the sentence those are not mentioned." 

Real numbers are also complex numbers with the imaginary part equal to 0 ;) . We're not cheating in any way. We are only making sure that your function it's working in every possible scenario.
